---
knitr: bookdown::render_book
title: "Modeling"
author: "Sara Altman, Bill Behrman"
date: "`r Sys.Date()`"
description: "This book is a practical introduction to modeling using the tidyverse."
url: 'https\://dcl-model.stanford.edu'
github-repo: dcl-docs/model
site: bookdown::bookdown_site
documentclass: book
bibliography: references.bib
link-citations: true
---

# Welcome {-}


## How to read this book {-}

All datasets used in this book are contained in R packages, making it easy to follow along and replicate our examples. Many of the datasets are in our own [dddata package](https://github.com/dcl-docs/dddata). You can install dddata from GitHub with

`devtools::install_github("dcl-docs/dddata")`

To access the datasets, load the relevant package

`library(dddata)`

and then call the name of the dataset

`anscombe_1`

All datasets have accompanying documentation, which you can find with 

`?{name of the dataset}`

## An evolving book {-}

This book is not intended to be static. Starting in January 2020, we use this book to teach modeling in the Stanford [Data Challenge Lab](https://datalab.stanford.edu/challenge-lab) (DCL) course. The DCL functions as a testing ground for educational materials, as our students give us routine feedback on what they read and do in the course. We use this feedback to constantly improve our materials, including this book. The [source for the book](https://github.com/dcl-docs/model) is also available on GitHub where we welcome suggestions for improvements.

This work is licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/). 
